config/routes.rb
Rails.application.routes.draw do
  
  root 'home#special-fashion'
  
  resources :questions
  
  devise_for :users
  
  post '/questions/:question_id' =>"questionreplys#create"
  
  delete '/questions/:question_id/questionreplys/:id' =>"questionreplys#destroy"
  
  post '/questions/:question_id/questionreplys/:id' =>"questionreplys#update"
  
  get '/home/elements-accordions' => 'home#elements-accordions'
  get '/home/elements-buttons' => 'home#elements-buttons'
  get '/home/elements-forms' => 'home#elements-forms'
  get '/home/elements-icons-et' => 'home#elements-icons-et'
  get '/home/elements-icons-fe'=> 'home#elements-icons-fe'
  get '/home/elements-tabs' => 'home#elements-tabs'
  get '/home/pages-account' => 'home#pages-account'
  get '/attend/register' => 'attend#register'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    if user.admin?
      can :manage, :all
    else if user.univadmin?
      can :manage, :all
    else
      can :create, Question
      can :read, Question
      can :update, Question do |question|
        question.user == user
    end
      can :delete, Question do |question|
        question.user == user
    end
      can :create, Questionreply
      can :read, Questionreply
      can :update, Questionreply do |questionreply|
          questionreply.user == user
    end
    can :delete, Questionreply do |questionreply|
        questionreply.user == user
    end
    
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    end
  end
end

app/models/join.rb
class Join < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :questionreplys
end

app/models/questionreply.rb
class Questionreply < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        
  has_many :questions
  has_many :questionreplys
end

app/controllers/application_controller.rb
require "font-awesome-rails"

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :univ])
  end

end

app/controllers/attend_controller.rb
class AttendController < ApplicationController
    def register
        @joins = Join.all
    end
    
    def create
        Join.create(content: params[:content], image: params[:image])
        redirect_to :back
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    def special_fashion

    end

end

app/controllers/questionreplys_controller.rb
class QuestionreplysController < ApplicationController
    
    def create
        @question = Question.find(params[:question_id])
        @questionreply = @question.questionreplys.new
        @questionreply.questionreply = params[:questionreply]
        @questionreply.user_id = params[:user_id]
        @questionreply.save
        
        redirect_to @question
    end
    
    def destroy
        @question = Question.find(params[:question_id])
        @questionreply = @question.questionreplys.find(params[:id])
        @questionreply.destroy
        
        redirect_to @question
    end
    
    def update
        @question = Question.find(params[:question_id])
        @questionreply = @question.questionreplys.find(params[:id])
        @questionreply.questionreply = params[:questionreply]
        @questionreply.user_id = params[:user_id]
        @questionreply.save
        
        redirect_to @question
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attend_helper.rb
module AttendHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questionreplys_helper.rb
module QuestionreplysHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/attend/register.html.erb
<html>
    <head>
        <title>Rhythm &mdash; One & Multi Page Creative Theme</title>
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta charset="utf-8">
        <meta name="author" content="Roman Kirichik">
        <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
</head>
<body class="appear-animate">
<section class="page-section">
                <div class="container relative">
                    
                    <h2 class="section-title font-alt mb-70 mb-sm-40">
                        Different Types
                    </h2>
                    
                    <!-- Row -->
                    <div class="row">
                        
                        <!-- Col -->
                        
                        <div class="col-sm-4 mb-40">
                            
                            <!-- Form -->
                            <form method="post" action="#" id="form" role="form" class="form">
                                
                                <div class="mb-20 mb-md-10">
                                    <!-- Name -->
                                    <input type="text" name="name" id="name" class="input-md form-control" placeholder="Name" maxlength="100">
                                </div>
                                
                                <div class="mb-20 mb-md-10">
                                    <!-- Email -->
                                    <input type="email" name="email" id="email" class="input-md form-control" placeholder="Email" maxlength="100">
                                </div>    
                                
                                <div class="mb-20 mb-md-10">
                                    <!-- Password -->
                                    <input type="password" name="password" id="password" class="input-md form-control" placeholder="Password" maxlength="100">
                                </div>
                                
                                <div class="mb-20 mb-md-10">
                                    <textarea name="text" id="text" class="input-md form-control" rows="8" placeholder="Text" maxlength="400"></textarea>
                                </div>
                                                            
                            </form>
							<!-- End Form -->
                            
                        </div>
                        
                        <!-- End Col -->
                        
                        <!-- Col -->
                        
                        <div class="col-sm-4 mb-40">
                            
                            <!-- Form -->
                            <form method="post" action="#" id="form-1" role="form" class="form">
                                
                                <div class="mb-20 mb-md-10">
                                    <select class="input-md form-control">
                                        <option>One</option>
                                        <option>Two</option>
                                        <option>Three</option>
                                    </select>
                                </div>
                                
                                <div class="mb-20 mb-md-10">
                                    <select multiple class="form-control">
                                        <option>One</option>
                                        <option>Two</option>
                                        <option>Three</option>
                                        <option>Four</option>
                                        <option>Five</option>
                                    </select>
                                </div>
                                
                                
                                <div class="mb-20 mb-md-10">
                                    <!-- Date-->
                                    <input type="date" name="date" id="date" class="input-md form-control">
                                </div>
                                
                                <div class="mb-20 mb-md-10">
                                    <!-- Color-->
                                    <input type="color" name="color" id="color" class="input-md form-control">
                                </div>
                                
                                <div class="mb-20 mb-md-10">
                                    <!-- Number -->
                                    <input type="number" name="number" id="number" class="input-md form-control" placeholder="0" max="100">
                                </div>   
                                
                            </form>
							<!-- End Form -->
                            
                        </div>
                        
                        <!-- End Col -->
                        
                        <!-- Col -->
                        
                        <div class="col-sm-4 mb-40">
                            
                            <!-- Form -->
                            <form method="post" action="#" id="form-2" role="form" class="form">
                                
                                <div class="mb-20 mb-md-10">
                                    <input class="input-md form-control" id="disabledInput" type="text" placeholder="Disabled input here..." disabled>
                                </div> 
                                
                                <div class="mb-20 mb-md-10">
                                    <label for="exampleInputFile">
                                        File input
                                    </label>
                                    
                                    <input type="file" id="exampleInputFile" action="/create", method:'POST'>
                                    <% @joins.each do |p| %>
            <li><%= p.id%>. <%= p.content %>
            <img src="<%= p.image.url %>">
            </li>
            <%end%>
                                    <p class="help-block">
                                        Example block-level help text here.
                                    </p>
                                </div>
                                
                                <div class="mb-20 mb-md-10">
                                    <label class="checkbox-inline">
                                        <input type="checkbox" id="inlineCheckbox1" value="option1">1
                                    </label>
                                    <label class="checkbox-inline">
                                        <input type="checkbox" id="inlineCheckbox2" value="option2">2
                                    </label>
                                    <label class="checkbox-inline">
                                        <input type="checkbox" id="inlineCheckbox3" value="option3">3
                                    </label>
                                </div>
                                
                                <div class="mb-20 mb-md-10">
                                    <label class="radio-inline">
                                        <input type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">1
                                    </label>
                                    <label class="radio-inline">
                                        <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">2
                                    </label>
                                    <label class="radio-inline">
                                        <input type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3">3
                                    </label>
                                </div>                                
                                
								
                            </form>
							<!-- End Form -->
                            
                        </div>
                        
                        <!-- End Col -->
                        
                    </div>
                    <!-- End Row -->
                    
                </div>
            </section>
            <!-- End Section -->
            
            
            <!-- Divider -->
            <hr class="mt-0 mb-0 "/>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta charset="utf-8">
  <meta name="author" content="Roman Kirichik">
  <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
  
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <!-- Favicons -->
  <link rel="shortcut icon" src="/assets/favicon.png">


  <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

  <!-- 부가적인 테마 -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  
  
  <!-- CSS -->
  <link rel="stylesheet" href="assets/bootstrap.min.css">
  <link rel="stylesheet" href="assets/style.css">
  <link rel="stylesheet" href="assets/style-responsive.css">
  <link rel="stylesheet" href="assets/animate.min.css">
  <link rel="stylesheet" href="assets/vertical-rhythm.min.css">
  <link rel="stylesheet" href="assets/owl.carousel.css">
  <link rel="stylesheet" href="assets/magnific-popup.css">  
  <!-- 합쳐지고 최소화된 최신 CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  
  
</head>


<body>
<%= render partial: "shared/nav" %>
<div class="container">
<%= yield %>
</div>
<%= render partial: "shared/footer" %>

<!-- JS -->
        <script type="text/javascript" src="assets/jquery-1.11.2.min.js"></script>
        <script type="text/javascript" src="assets/jquery.easing.1.3.js"></script>
        <script type="text/javascript" src="assets/bootstrap.min.js"></script>        
        <script type="text/javascript" src="assets/SmoothScroll.js"></script>
        <script type="text/javascript" src="assets/jquery.scrollTo.min.js"></script>
        <script type="text/javascript" src="assets/jquery.localScroll.min.js"></script>
        <script type="text/javascript" src="assets/jquery.viewport.mini.js"></script>
        <script type="text/javascript" src="assets/jquery.countTo.js"></script>
        <script type="text/javascript" src="assets/jquery.appear.js"></script>
        <script type="text/javascript" src="assets/jquery.sticky.js"></script>
        <script type="text/javascript" src="assets/jquery.parallax-1.1.3.js"></script>
        <script type="text/javascript" src="assets/jquery.fitvids.js"></script>
        <script type="text/javascript" src="assets/owl.carousel.min.js"></script>
        <script type="text/javascript" src="assets/isotope.pkgd.min.js"></script>
        <script type="text/javascript" src="assets/imagesloaded.pkgd.min.js"></script>
        <script type="text/javascript" src="assets/jquery.magnific-popup.min.js"></script>
        <!-- Replace test API Key "AIzaSyAZsDkJFLS0b59q7cmW0EprwfcfUA8d9dg" with your own one below 
        **** You can get API Key here - https://developers.google.com/maps/documentation/javascript/get-api-key -->
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAZsDkJFLS0b59q7cmW0EprwfcfUA8d9dg"></script>
        <script type="text/javascript" src="assets/gmap3.min.js"></script>
        <script type="text/javascript" src="assets/wow.min.js"></script>
        <script type="text/javascript" src="assets/masonry.pkgd.min.js"></script>
        <script type="text/javascript" src="assets/jquery.simple-text-rotator.min.js"></script>
        <script type="text/javascript" src="assets/all.js"></script>
        <script type="text/javascript" src="assets/contact-form.js"></script>
        <script type="text/javascript" src="assets/jquery.ajaxchimp.min.js"></script>

        <!--[if lt IE 10]><script type="text/javascript" src="assets/placeholder.js"></script><![endif]-->
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"제목" %><br>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :내용 %><br>
    <%= f.text_area :content, class:"form-control" %>
  </div>
  <div class="field">
    
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit "글쓰기", class:"btn btn-default" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div class="container">

<h1>Q & A 게시판</h1>

<table class="table">
  <thead>
    <tr>
      <th>제목</th>
      
      <th>작성자</th>
     
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to question.title, question %></td>
        
        
        <td><%= question.user.name %></td>
        
        
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

</div>

app/views/questions/new.html.erb
<div class="container">
    <h1>새 질문 작성</h1>
    
    <%= render 'form' %>
    
    <%= link_to 'Back', questions_path %>
</div>

app/views/questions/show.html.erb
<div class="container">
  
  <h2><%= @question.title %></h2>
  <hr>
  
  <p><strong>내용</strong></p>
  <p><%= @question.content %></p>
  <hr>
  
  <p><strong>작성자</strong></p>
  <p><%= @question.user.name %></p>
  <hr>
  <% if can? :update, @question %>
    <%= link_to 'Edit', edit_question_path(@question) %> |
  <% end %>
  <%= link_to 'Back', questions_path %> |
  <% if can? :delete, @question %>
  <%= link_to 'Destroy', @question, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
  <hr>
  <p><strong>댓글작성</strong></p>
  <div class="well">
    <form action="/questions/<%=@question.id%>" method="post">
      <div class="form-group">
        <input type="hidden" value="<%=current_user.id%>" name="user_id"></input>
        <input type="hidden" value="<%=@question.id%>" name="question_id"></input>
        <textarea class="form-control" rows="5" name="questionreply"></textarea>
      </div>
      <button type="submit" class="btn btn-default">댓글작성!</button>
    </form>
  </div>
  <hr>
  <p><strong>댓글목록</strong></p>
  <% @questionreplys = @question.questionreplys.all.reverse %>
  <% @questionreplys.each do |c| %>
  <div class="well">
  <p class="original-questionreply" id="<%=c.id %>">작성자 : <%= c.user.email %></p>
  <p class="original-questionreply" id="<%=c.id %>">내용 : <%= c.questionreply %></p>
  <div class="edit-questionreply-<%=c.id%>" style="display:none;">
    <form action="/questions/<%=@question.id%>/questionreplys/<%=c.id%>" method="post">
      <div class="form-group">
        <input type="hidden" value="<%=current_user.id%>" name="user_id"></input>
        <input type="hidden" value="<%=@question.id%>" name="question_id"></input>
        <textarea class="form-control" rows="5" name="questionreply"><%=c.questionreply %></textarea>
      </div>
      <button type="submit" class="btn btn-default">수정완료!</button>
    </form>
    </br>
  </div>
  <div class="edit-questionreply-<%=c.id%>-button-group">
    <% if can? :update, c %>
    <button class="btn btn-default edit-button" id="edit-questionreply-<%=c.id %>">수정</button>
    <% end %>
    <% if can? :delete, c %>
    <a href="/questions/<%=@question.id%>/questionreplys/<%=c.id%>" data-method="delete" class="btn btn-default">삭제</a>
    <% end %>
  </div>
  </div>
  <% end %>
</div>

<script>
  $(".edit-button").click(function() {
    var clickedID = this.id;
    $("."+clickedID).css("display","block");
    $("."+clickedID+"-button-group").css("display","none");
  });
  
</script>

app/views/shared/_nav.html.erb
<!-- Navigation panel -->
            <nav class="main-nav js-stick" >
                <div class="container">
                <div class="full-wrapper relative clearfix">
                    <!-- Logo ( * your text or image into link tag *) -->
                    <div class="nav-logo-wrap local-scroll">
                        <a href="/" class="logo">
                           Flea
                        </a>
                    </div>
                    <div class="mobile-nav">
                        <i class="fa fa-bars"></i>
                    </div>
                    
                    <!-- Main Menu -->
                    <div class="inner-nav desktop-nav">
                        <ul class="clearlist" style="font-size: 16px !important;
													font-weight: bold !important;
													">
                            
                            <!-- Item With Sub -->
                            <li>
                                <a href="#" class="mn-has-sub">공지사항 <i class="fa fa-angle-down"></i></a>
                                
                                
                            </li>
                            <!-- End Item With Sub -->
                            
                            <!-- Item With Sub -->
                            <li>
                                <a href="#" class="mn-has-sub">이번 주 참가현황 <i class="fa fa-angle-down"></i></a>
                                
                                
                                
                            </li>
                            <!-- End Item With Sub -->
                            
                            <!-- Item With Sub -->
                            <li>
                                <a href="/attend/register">참가신청 </a>
                                
                                
                            </li>
                            <!-- End Item With Sub -->
                            
                            <!-- Item With Sub -->
                            <li>
                                <a href="/questions" class="mn-has-sub">Q & A <i class="fa fa-angle-down"></i></a>
                                
                                
                            </li>
                            <!-- End Item With Sub -->
                            
                            <!-- Item With Sub -->
                            <% if user_signed_in? %>
                            <li class="dropdown">
					          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
					          	반갑습니다 <span class="caret"></span></a>
					          <ul class="dropdown-menu" role="menu">
					            <span class="navbar-text" style="padding-left: 24px;">
					            <strong><%= current_user.name %></strong><br /> 으로 로그인 함</span>
					            <li class="divider"></li>
					            
					            <li><a href="#">프로필</a></li>
					            <li><a href="#">Something else here</a></li>
					            
					            <li class="divider"></li>
					            <li><a href="/users/edit">회원정보 수정</a></li>
					            <li><a href="/users/sign_out">로그아웃</a></li>
					          </ul>
        					</li>
                            
                            <% else %>
                            <li>
                                <a href="/users/sign_in">로그인</a>
                                
                                
                                
                            </li>
                            <!-- End Item With Sub -->
                            
                            <!-- Item With Sub -->
                            <li>
                                <a href="/users/sign_up" class="active">회원가입</a>
                                
                            </li>
                            <!-- End Item With Sub -->
                            <% end %>
                            
                           
                        </ul>
                    </div>
                    <!-- End Main Menu -->
                    

                </div>
                </div>
            </nav>
            <!-- End Navigation panel -->
            